---
title: "week2-rexercise"
output: html_document
date: "2023-04-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1
```{r}
library("readr") 
library("sf") 
```

```{r}
wildschwein_BE <- read_delim("data/wildschwein_BE_2056.csv", ",")

wildschwein_BE <- st_as_sf(wildschwein_BE, coords = c("E", "N"), crs = 2056, remove = FALSE)
```

# Task 2
```{r}
library("dplyr")
library("ggplot2")
```

```{r}
# Calculate the time difference between subsequent rows
# seconds

wildschwein_BE <- wildschwein_BE |>
  group_by(TierID) |>
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")))
```

```{r}
# How many individuals were tracked?

num_individuals <- wildschwein_BE$TierID |>
  unique() |>
  length()

num_individuals
```

```{r}
# For how long were the individual tracked? Are there gaps?
# Here a gap is defined as more than 1 hour between fixes

individual_duration <- wildschwein_BE |>
  group_by(TierID) |>
  summarise(start_time = min(DatetimeUTC),
            end_time = max(DatetimeUTC),
            duration = as.numeric(difftime(end_time, start_time, units = "hours")),
            n_gaps = sum(length(which(timelag > 3600))))

individual_duration
```

```{r}
# Were all individuals tracked concurrently or sequentially?

ggplot(wildschwein_BE, aes(DatetimeUTC, TierName)) + geom_point()

# We can see from the plot that they were tracked concurrently.
```

```{r}
# What is the temporal sampling interval between the locations?

sampling_interval <- wildschwein_BE |>
  group_by(TierID) |>
  summarise(mean_interval = mean(timelag, na.rm = TRUE),
            median_interval = median(timelag, na.rm = TRUE))

sampling_interval
```

# Task 3
```{r}
# Calculate the animal’s steplength
# meters

wildschwein_BE <- wildschwein_BE |>
  group_by(TierName) |>
  mutate(steplength = sqrt((E - lead(E))^2 + (N - lead(N))^2))
```

```{r}
# Calculate the animals’ speed between consecutive locations
# meters/second

wildschwein_BE <- wildschwein_BE |>
  mutate(speed = steplength / timelag)
```

# Task 4
```{r}
caro <- read_delim("data/caro60.csv", ",")

caro <- st_as_sf(caro, coords = c("E", "N"), crs = 2056, remove = FALSE)
```

```{r}
# Reduce the granularity of our sampling interval

caro_3 <- caro[seq(1, nrow(caro), by = 3), ]
caro_6 <- caro[seq(1, nrow(caro), by = 6), ]
caro_9 <- caro[seq(1, nrow(caro), by = 9), ]
```

```{r}
# Calculate timelag, steplength and speed

caro <- caro |>
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")),
         steplength = sqrt((E - lead(E))^2 + (N - lead(N))^2),
         speed = steplength / timelag)

caro_3 <- caro_3 |>
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")),
         steplength = sqrt((E - lead(E))^2 + (N - lead(N))^2),
         speed = steplength / timelag)

caro_6 <- caro_6 |>
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")),
         steplength = sqrt((E - lead(E))^2 + (N - lead(N))^2),
         speed = steplength / timelag)

caro_9 <- caro_9 |>
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")),
         steplength = sqrt((E - lead(E))^2 + (N - lead(N))^2),
         speed = steplength / timelag)
```

```{r}
# visualize the trajectories in a map

ggplot() +
  geom_path(data = caro, aes(x = E, y = N), color = "blue", alpha = 0.5) +
  geom_path(data = caro_3, aes(x = E, y = N), color = "red", alpha = 0.5) +
  geom_point(data = caro, aes(x = E, y = N), color = "blue", alpha = 0.5) +
  geom_point(data = caro_3, aes(x = E, y = N), color = "red", alpha = 0.5) +
  labs(title = "Comparing original- with 3 minutes-resampled data",
       x = "E",
       y = "N")

ggplot() +
  geom_path(data = caro, aes(x = E, y = N), color = "blue", alpha = 0.5) +
  geom_path(data = caro_6, aes(x = E, y = N), color = "red", alpha = 0.5) +
  geom_point(data = caro, aes(x = E, y = N), color = "blue", alpha = 0.5) +
  geom_point(data = caro_6, aes(x = E, y = N), color = "red", alpha = 0.5) +
  labs(title = "Comparing original- with 6 minutes-resampled data",
       x = "E",
       y = "N")

ggplot() +
  geom_path(data = caro, aes(x = E, y = N), color = "blue", alpha = 0.5) +
  geom_path(data = caro_9, aes(x = E, y = N), color = "red", alpha = 0.5) +
  geom_point(data = caro, aes(x = E, y = N), color = "blue", alpha = 0.5) +
  geom_point(data = caro_9, aes(x = E, y = N), color = "red", alpha = 0.5) +
  labs(title = "Comparing original- with 9 minutes-resampled data",
       x = "E",
       y = "N")
```

```{r}
# compare the speeds visually in a line plot

ggplot() +
  geom_line(data = caro, aes(x = DatetimeUTC, y = speed, color = "Original"), na.rm = TRUE) +
  geom_line(data = caro_3, aes(x = DatetimeUTC, y = speed, color = "Every 3rd"), na.rm = TRUE) +
  geom_line(data = caro_6, aes(x = DatetimeUTC, y = speed, color = "Every 6th"), na.rm = TRUE) +
  geom_line(data = caro_9, aes(x = DatetimeUTC, y = speed, color = "Every 9th"), na.rm = TRUE) +
  labs(title = "Comparing derived speeds at different sampling intervals",
       x = "Time",
       y = "Speed (m/s)",
       color = "Sampling interval")
```

